#!/bin/bash

# =============================================================================
# DEPLOY SCRIPT - RENDER
# Instruções para deploy no Render
# =============================================================================

echo "🎨 Deploy no Render - Instruções"
echo "================================="
echo ""
echo "1️⃣  Acesse https://render.com e crie uma conta"
echo ""
echo "2️⃣  Crie um novo Web Service:"
echo "   - Connect GitHub repository"
echo "   - Runtime: Docker"
echo "   - Build Command: (deixe vazio)"
echo "   - Start Command: (deixe vazio)"
echo ""
echo "3️⃣  Configure as variáveis de ambiente:"
echo ""
echo "🔧 VARIÁVEIS OBRIGATÓRIAS:"
echo "   ASPNETCORE_ENVIRONMENT=Production"
echo "   ASPNETCORE_URLS=http://+:10000"
echo "   UseEntityFramework=true"
echo ""
echo "🔐 JWT:"
echo "   Jwt__Secret=$(openssl rand -base64 32)"
echo "   Jwt__Issuer=PedidoRapido.API"
echo "   Jwt__Audience=PedidoRapido.Frontend"
echo ""
echo "🗄️  POSTGRESQL:"
echo "   - Crie um PostgreSQL database no Render"
echo "   - Copie a Internal Database URL"
echo "   ConnectionStrings__DefaultConnection=postgresql://..."
echo ""
echo "🌐 CORS:"
echo "   CORS__AllowedOrigins=https://seudominio.com"
echo ""
echo "💳 STRIPE:"
echo "   Stripe__SecretKey=sk_live_..."
echo "   Stripe__PublicKey=pk_live_..."
echo "   Stripe__WebhookSecret=whsec_..."
echo ""
echo "4️⃣  Configure o Dockerfile:"
echo "   - Certifique-se que o Dockerfile está na raiz do repositório"
echo "   - Render detectará automaticamente"
echo ""
echo "5️⃣  Deploy:"
echo "   - Clique em 'Create Web Service'"
echo "   - Aguarde o build e deploy"
echo ""
echo "6️⃣  Verificar:"
echo "   - Acesse https://seuapp.onrender.com/health"
echo "   - Verifique os logs no dashboard"
echo ""
echo "📚 Documentação: https://render.com/docs/docker"
echo ""